token_url: "https://api-quanto.com/v1/api/tokenv"
client_id: "6abc0c4b-9ea7-41ce-b4ce-7465a4db20d5"
client_secret: "0cAHIMTwrj0pW3TdyNBctTiaaSpufRnh"
grant_type: "client_credentials"
participants_url: "https://api-quanto.com/opb-api/v1/participants/payments"
payment_url: "https://api-quanto.com/opb-api/v1/payments"
production_url: "http://www.cafedoamigo.com.br/"
redis_dbname: "apis"
redis_server: "localhost:6379"
redis_password: ""